---
- name: Configure Mac Studio (Linux Test)
  hosts: localhost
  connection: local
  tasks:
    - name: Install Linux packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - zsh
        - openjdk-17-jdk
        - podman
      become: yes
      when: ansible_os_family == 'Debian'
      tags: packages

    - name: Verify Linux packages are installed
      stat:
        path: "{{ item }}"
      loop:
        - /usr/bin/zsh
        - /usr/bin/java
        - /usr/bin/podman
      register: package_check
      failed_when: not package_check.stat.exists
      when: ansible_os_family == 'Debian'
      tags: packages

    - name: Ensure Podman is configured
      command: podman system service --time=0 &
      register: podman_service
      changed_when: false
      failed_when: podman_service.rc != 0
      when: ansible_os_family == 'Debian'
      tags: podman

    - name: Verify Podman networking
      command: podman run --rm -p 8080:80 docker.io/library/nginx
      register: podman_nginx
      async: 5
      poll: 0
      when: ansible_os_family == 'Debian'
      tags: podman

    - name: Check Podman port forwarding
      command: curl -s http://localhost:8080
      register: podman_curl
      failed_when: "'Welcome to nginx' not in podman_curl.stdout"
      when: ansible_os_family == 'Debian'
      tags: podman

    - name: Stop Podman test container
      command: podman stop $(podman ps -q)
      when: podman_nginx is success
      ignore_errors: true
      when: ansible_os_family == 'Debian'
      tags: podman

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
      args:
        creates: ~/.oh-my-zsh
      tags: zsh

    - name: Verify Oh My Zsh is installed
      stat:
        path: ~/.oh-my-zsh/oh-my-zsh.sh
      register: ohmyzsh_check
      failed_when: not ohmyzsh_check.stat.exists
      tags: zsh

    - name: Set zsh as default shell
      shell: chsh -s /bin/zsh
      become: yes
      tags: zsh

    - name: Verify zsh is the default shell
      command: echo $SHELL
      register: shell_check
      changed_when: false
      failed_when: shell_check.stdout != "/bin/zsh"
      tags: zsh

    - name: Final success message
      debug:
        msg: "All components installed and configured successfully (WSL test)!"
      when: package_check is success and podman_curl is success and ohmyzsh_result is success and shell_result is success 
      tags: [packages, podman, zsh, dotfiles]
